# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=300, verbose_name='产品名称')),
                ('p_brand', models.CharField(max_length=300, validators=['品', '牌'])),
                ('p_price', models.FloatField(max_length=6, verbose_name='价格')),
                ('p_image', models.URLField(verbose_name='图片地址')),
                ('p_url', models.URLField(verbose_name='商品地址')),
                ('p_id', models.IntegerField(verbose_name='商品ID')),
                ('p_platform', models.CharField(default='淘宝', max_length=20, verbose_name='电商平台')),
            ],
        ),
    ]
