# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='评论')),
            ],
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='p_brand',
            field=models.CharField(max_length=300, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='productcomm',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommentsSys.ProductInfo'),
        ),
    ]
