# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsSys', '0002_auto_20170930_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomm',
            name='comm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评论时间'),
        ),
        migrations.AddField(
            model_name='productcomm',
            name='comm_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='评论ID'),
        ),
        migrations.AddField(
            model_name='productcomm',
            name='comm_nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='productcomm',
            name='comm_sku',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SKU'),
        ),
    ]
