# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsSys', '0003_auto_20170930_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(verbose_name='买家秀地图片')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productcomm',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='productcommimage',
            name='product_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommentsSys.ProductComm'),
        ),
    ]
